"""add last_edited field to Entry model

Revision ID: b0dd973e292f
Revises: bad37adb970d
Create Date: 2019-04-27 20:59:54.353483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0dd973e292f'
down_revision = 'bad37adb970d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('last_edited', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'last_edited')
    # ### end Alembic commands ###
